meta:
  Type: Mapped
  ID: SITE
  Description: Site Metadata
  Priority: 2
spec:
  Mapped_DM:
    SITEID:
      type: character
    USUBJID:
      type: character
    timeonstudy:
      type: numeric
steps:
  # Count the number of participants at each site.
  - output: ParticipantCounts
    name: RunQuery
    params:
      df: Mapped_DM
      strQuery: |
        SELECT
          SITEID as GroupID,
          'Site ' || SITEID as InvestigatorLastName,
          COUNT(DISTINCT USUBJID) as ParticipantCount
        FROM df
        GROUP BY SITEID

  # Transpose site metadata to one row per site per attribute.
  - output: Mapped_SITE
    name: MakeLongMeta
    params:
      data: ParticipantCounts
      strGroupLevel: "Site"

